version: '3'

services:
  portfolio:
    command: yarn
    container_name: portfolio
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./:/app
    ports:
      - 55020:8080
